### PR TITLE
Josh

### LINKED ISSUE #53: DFD 4 + Report

### LINKED ISSUE #58: DFD 4 Summary Of Observations

### PR DESCRIPTION
**Pull request by jmpinoy**
Added #53 DFD 4 + report

### CODE REVIEW

**Review by Chrs987 — DISMISSED** [review]
I have read through your report and looked at your diagram and think you did a good job covering all the threats that HA mitigated and those that were not applicable. I look forward to your brief summary. Also good idea creating a reports folder for the PDF files.

**Comment by Chrs987** [comment]
Just as a follow up, it may be worth noting that the process that HA updates addons with is `supervisor.store.git` so we may want to change the middle process to that instead of Home Assistant Server.

**Review by Jbibianochavez — APPROVED** [review]
Looked over the document, everything looks good.

**Review by Chrs987 — APPROVED** [review]
Everything looks good!

**Pull request merged**
